### ISSUE TITLE
Still bugs

### ISSUE THREAD

**Issue by depoods** [depoods/staticsite#2]
<enum 'TextNodeType'>
text nodeTextNode(Bold Text, <enum 'TextNodeType'>, None)
.<enum 'TextNodeType'>
text nodeTextNode(Sample Text, <enum 'TextNodeType'>, None)
E.
======================================================================
ERROR: test_text_node_conversion (test_htmlnode.TestTextNodeToHtmlNode.test_text_node_conversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/depood/workspace/github.com/depoods/staticsite/src/test_htmlnode.py", line 101, in test_text_node_conversion
    result = text_node_to_html_node(text_node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/depood/workspace/github.com/depoods/staticsite/src/htmlnode.py", line 89, in text_node_to_html_node
    return LeafNode(value=text_node.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LeafNode.__init__() missing 1 required positional argument: 'tag'

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=1)
<enum 'TextNodeType'>
text nodeTextNode(Bold Text, <enum 'TextNodeType'>, None)
.<enum 'TextNodeType'>
text nodeTextNode(Sample Text, <enum 'TextNodeType'>, None)
E
======================================================================
ERROR: test_text_node_conversion (__main__.TestTextNodeToHtmlNode.test_text_node_conversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/depood/workspace/github.com/depoods/staticsite/src/test_htmlnode.py", line 101, in test_text_node_conversion
    result = text_node_to_html_node(text_node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/depood/workspace/github.com/depoods/staticsite/src/htmlnode.py", line 89, in text_node_to_html_node
    return LeafNode(value=text_node.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LeafNode.__init__() missing 1 required positional argument: 'tag'

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=1)

**Comment by depoods** [comment]
Fixed
